pub mod abs;
pub mod add;
pub mod ceil;
pub mod clamp;
pub mod divide;
pub mod floor;
pub mod fract;
pub mod is_finite;
pub mod is_infinite;
pub mod is_nan;
pub mod max;
pub mod min;
pub mod multiply;
pub mod negate;
pub mod pow;
pub mod remainder;
pub mod round;
pub mod subtract;
pub mod trunc;

pub use abs::{Abs, FloatAbs};
pub use add::{Add, FloatAdd};
pub use ceil::FloatCeil;
pub use clamp::{FloatClamp, IntegerClamp};
pub use divide::{Divide, FloatDivide};
pub use floor::FloatFloor;
pub use fract::FloatFract;
pub use is_finite::FloatIsFinite;
pub use is_infinite::FloatIsInfinite;
pub use is_nan::FloatIsNan;
pub use max::{FloatMax, IntegerMax};
pub use min::{FloatMin, IntegerMin};
pub use multiply::{FloatMultiply, Multiply};
pub use negate::{FloatNegate, Negate};
pub use pow::Pow;
pub use remainder::{FloatRemainder, Remainder};
pub use round::FloatRound;
pub use subtract::{FloatSubtract, Subtract};
pub use trunc::FloatTrunc;
